backend:
  name: git-gateway
  repo: aviemet/portfolio
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'blog/{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { name: 'templateKey', label: 'Template Key', required: true, widget: 'hidden', default: 'blog'}
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'datetime' }
      - { name: 'description', label: 'Description', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'project'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: 'projects/{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor: 
      preview: true
    fields:
      - { name: 'templateKey', label: 'Template Key', required: true, widget: 'hidden', default: 'project'}
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'datetime' }
      - { name: 'description', label: 'Description', widget: 'string' }
      - { name: 'image', label: 'Image', widget: 'image' }
      - { name: 'body', label: 'Body', widget: 'markdown' }