backend:
  name: git-gateway
  repo: aviemet/portfolio
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'datetime' }
      - { name: 'description', label: 'Description', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }